# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":td"
    replace: "[TODO]"

  - trigger: ":qe"
    replace: "[QUOTE]"

  - trigger: ":ml"
    replace: "[MEAL]"

  - trigger: ":et"
    replace: "[EVENT]"

  - trigger: ":wl"
    replace: "[WORKOUT] [Exercise] – [Weight] – [Sets] x [Reps]"

  - trigger: ":dq"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: cat ~/dq.txt

  # Dates
  - trigger: ":datetime"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y %H:%M:%S"

  - trigger: ":bl"
    replace: "[[Brain Log]] {{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y %H:%M:%S"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
